### ISSUE TITLE
lab3 FSM Coding style관련 질문 (Moore vs Mealy)

### ISSUE THREAD

**Issue by gju06051** [ECE4278/lab3#1]
안녕하세요. lab3 DMA_ENGINE에 사용되는 FSM과 관련해서 질문이 있어서 남기게 됩니다.
FSM이라는 것이 특정 state에서 필요한 control signal을 생성하기 위한 controller를 설계할 때 많이 들 사용한다고 알고 있습니다.

해당 lab과 같은 경우에는 특정 state에서 AXI의 handshake를 위한 valid나 ready신호를 생성하는데 사용되고 있고, 

또한 특정 state들에서 transition될 때마다 해야 하는 동작(ex. capture,  increment addr 4)을 하는데 사용되고 있습니다. valid나 ready신호는 이해가 되는데 뭔가 'transition될 때마다 수행하는 동작'이 기존의 fsm 사용하는 방법과 좀 다른 거 같아서 질문 드립니다.

예를 들어 IDLE에서 RREQ로 transition할 때 몇 가지 값들을 capture하는 동작이 있습니다. 이 동작은 IDLE이나 RREQ나 하나의 state에서 머무르고 있을 때 반복적으로 수행되는 것이 아니라 transition할 때 단 1번 수행되는 동작입니다. 

그렇다면 해당 FSM은 특정 state에서 다른 state로 transition를 할 때 수행됨으로 transition을 위한 조건인 input값과 현재 state에 의해서 동작이 수행됨으로 mealy로 보았는데 이것이 맞는 분석인지 궁금합니다.

**Comment by dale40** [comment]
무어나 밀리나 다음 스테이트를 결정하는데는 인풋과 현재 상태를 입력으로 받습니다.
차이점은 아웃풋을 생성하는데 있습니다. 무어는 현재 상태만을 바텅으로 아웃풋을 생성하고 밀리는 현재 상태와 입력을  바탕으로 생성합니다. 랩에서 보여준 스테이트 테이블은 현재 상태만을 바탕으로 avalid등의 아웃풋을 생성하기 때문에 무어 머신입니다.

**Comment by gju06051** [comment]
답변 감사합니다. 
그런데 제가 혼란을 겪는 부분은 예를들어

IDLE->RREQ로 전이할 때 src_addr와 같은 값들을 CFG에서 받아와서 flipflop에 저장하게 되는데 이는 fsm에서 src_addr를 저장하는 flilflop에 enable신호를 주는 것처럼 생각하였습니다. 

그렇다면 해당 enable신호는 start신호와 현재 state인 IDLE에 의해서 생성되었다고 생각되어(start_i가 없을 경우는 src_addr이 update되지 않음으로) 따라서 mealy라 판단하였는데 잘못된 해석인가요?

각 state의 valid, ready신호 같은 경우는 moore인 것은 이해하였습니다.

**Comment by dale40** [comment]
src_addr같은 flip/flop에 들어가는 enable신호들도 아웃풋으로 생각하면 밀리 머신이 맞습니다.

**Comment by gju06051** [comment]
바쁘신 와중에 답변 감사합니다.
