### ISSUE TITLE
Verdi에서 add to waveform 클릭이 안되는 이유

### ISSUE THREAD

**Issue by john2554** [ECE4278/lab3#4]
sim이 정상적으로 작동하여 verdi에서 waveform을 보려고 했습니다.
그런데 add to waveform이 클릭이 안되는 상황입니다.

compile할 때 에러도 없었는데 혹시 어떤 이유로 클릭이 안되는지 알 수 있을까요?

**Comment by pdtowctor** [comment]
안녕하세요, SOC설계및실습 조교 박태원입니다.

Verdi 메뉴창에서 [Simulation] -> [Invoke Simulator] 혹은 Ctrl+Shift+r 해보시기 바랍니다.

혹시 위 방법으로도 안되면 다시 알려주시기 바랍니다.
